### ISSUE TITLE
Problème Cakebox

### ISSUE THREAD

**Issue by pldrbs** [Patlol/Handy-Install-Web-Server-ruTorrent-#3]
Hello, je suis un peu newbie sur Linux
J'ai lancé le script et tout fait comme il faut, il dit que tout est ok 
Mais quand j'essaie de télécharger un fichier dans Cakebox, tout est ok mais une fois que je clique dessus pour télécharger, je tombe sur une erreur 404 Not found. Que faire ?

**Comment by pldrbs** [comment]
J'ai réinstaller sans cocher l'option Webmin, et cela fonctionne parfaitement ...

**Comment by Patlol** [comment]
ok 
Curieux, je vais regarder ça 
Tu es sur nginx ou apache ?
Debian ou ubuntu ?
Dernière version du script ?

**Comment by Patlol** [comment]
pldrbs ???

**Comment by RHEiA31** [comment]
Bonjour,
J'ai le même soucis avec cakebox, impossible de télécharger un fichier, ça me renvoie une erreur 404 Not Found
Que puis-je faire ? =/
Je suis sous Ubuntu 16.04, et j'ai choisi nginx
Merci d'avance pour ton aide =$

**Comment by Patlol** [comment]
J'ai vu ça, il y a une erreur 404 avec nginx **mais c'est ok avec apache**. 
Très curieux, vu les modifs que j'ai faite depuis mes derniers tests ou c'était ok

Sur le dépôt de cakebox il y a [2 issues datant du 2 et 8 mars sur ce sujet](https://github.com/cakebox/cakebox/issues)  **restées sans réponse**  Aucun commit n'a été effectué depuis 5 mois ...

D'autre part la fonction principale de cakebox étant le streaming et pour cela ayant besoin d'un plugin vlc ou divX qui ne sont plus supporté par les navigateurs, y compris firefox, le dernier à les supporter. La solution HTML5 étant inopérante avec la plupart des codec vidéo que l'on trouve sur une seedbox. (seul mp4, webm et ogg sont supportés) **Je crains que cakebox soit en "fin de vie"** Je m'oriente vers une solution de remplacement comme owncloud

**En attendant pour utiliser cakebox installer apache2 !**

**Comment by RHEiA31** [comment]
Merci pour ta réponse.
Je suis en train d'essayer avec Apache2, là y'a carrément un soucis lors de l'install de ton script :

![vbxdfgfh](https://cloud.githubusercontent.com/assets/27552617/25063570/1054180e-21e8-11e7-9235-85d2d03d89b6.PNG)

**Comment by RHEiA31** [comment]
Bon et bien après moultes essais et réinstall, chez moi ça fonctionne uniquement sur :
▪ Debian 8, 64 bits
▪ Nginx

Merci à toi pour le script. 👍👍

**Comment by Patlol** [comment]
tu obtiens ça à quel étape de l'install ?
pour moi c'est la sortie de
`service apache2 status`
et `Active: active (running) `
indique que c'est ok 
As-tu essayé de lancer rutorrent ou cakebox sur ton navigateur ?

**Comment by RHEiA31** [comment]
Dans le script, apparemment c'était au moment de l'installation d'apache
J'ai donc réinstallé une énième fois mon serveur, cette fois sur Debian 8, puis réutilisé ton script en choisissant Nginx (puisqu'avec apache on a des soucis) et tout fonctionne impeccable =D
ruTorrent comme Cakebox

**Comment by Patlol** [comment]
Tu me dis qu'avec debian + nginx cakebox ne fait pas d'erreur 404 ?
Tant qu'au message de la copie d'écran ce n'est pas un message d'erreur, c'est un status correcte.
Ci dessous un status en erreur type :
![](http://img15.hostingpics.net/pics/266247Capturedcran20170415174834.png)

**Comment by RHEiA31** [comment]
C'était ptete un statut correct, mais le script s'arrêtait malheureusement là =/

Et sinon oui, effectivement, Debian + Nginx fonctionnent à merveille, plus d'erreur 404 ni aucune autre

**Comment by Patlol** [comment]
Le développement de cakebox n'est plus suivi. 
Ce que je peux dire c'est que pour moi après tests, cakebox fonctionne avec debian et ubuntu + apache2 et il y a erreur 404 avec debian et ubuntu + nginx
