### ISSUE TITLE
Apache2 & Ubuntu 16.04

### ISSUE THREAD

**Issue by Salvitri** [Patlol/Handy-Install-Web-Server-ruTorrent-#4]
Bonjour,
libapache2-mod-php5 n'est plus supporté, alors je pense qu'il faudrait ajouter : 
`apt-get install libapache2-mod-php`
sinon, le script s'arrête à l'étape d'installation d'apache2 sans donner de message d'erreur...
C'est tout bête mais pour les noob comme moi, ça n'a pas été facile de comprendre d'où venait le problème.
Sinon, merci pour ce super script !

**Comment by Patlol** [comment]
En principe avec ubuntu 16 c'est `libapache2-mod-php7.0` qui devrais s'installer. Par défaut Ubuntu 16 à php7.0 dans ~~ses dépôts officiels~~ fourni par ovh pour les vps.
`libapache2-mod-php5`  est encore utilisé pour Debian 8
Je regarde ça dans les meilleurs délais.

**Comment by Salvitri** [comment]
En fait `libapache2-mod-php7.0` n'existe pas, c'est `libapache2-mod-php` tout court (dans les dépôts officiels en tout cas). ;)

**Comment by Patlol** [comment]
Sur debian 9 les deux noms de paquets coexistent : 
```
$ sudo aptitude search libapache2-mod-php
p   libapache2-mod-php                                                                     - server-side, HTML-embedded scripting language (Apache 2 module) (default)                        
i   libapache2-mod-php7.0                                                                  - server-side, HTML-embedded scripting language (Apache 2 module)                                  
$ 
```
Je n'ai pas sous la main debian 8 et ubuntu 16 les deux autres distrib pour les quelles le script est prévu. Je regarde ça dès que j'ai 5 mn
**[edit]  
Là je suis sur Ubuntu 16.04.2 LTS sur un vps d'ovh**
j'ai aussi les 2 : 
```
# sudo aptitude search libapache2-mod-php
p   libapache2-mod-php                                                                     - server-side, HTML-embedded scripting language (Apache 2 module) (default)                        
i   libapache2-mod-php7.0                                                                  - server-side, HTML-embedded scripting language (Apache 2 module) 
```
```
# sudo aptitude show libapache2-mod-php
Package: libapache2-mod-php              
State: not installed
Version: 1:7.0+35ubuntu6
Priority: optional
Section: php
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 15.4 k
Depends: libapache2-mod-php7.0
Provided by: libapache2-mod-php7.0 (7.0.22-0ubuntu0.16.04.1), libapache2-mod-php7.0 (7.0.4-7ubuntu2)
Description: server-side, HTML-embedded scripting language (Apache 2 module) (default)
 This package provides the PHP module for the Apache 2 webserver. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded
 into HTML. 
 
 This package is a dependency package, which depends on Debian's default PHP version (currently 7.0).
```
**Depends: libapache2-mod-php7.0
Provided by: libapache2-mod-php7.0 (7.0.22-0ubuntu0.16.04.1), libapache2-mod-php7.0 (7.0.4-7ubuntu2)  
 This package is a dependency package, which depends on Debian's default PHP version (currently 7.0)**
Pour moi `libapache2-mod-php` est un nom générique de `libapache2-mod-php7.0` pour la version courrnate de php
Très curieux que apt-get install est planté la dessus. 
Sur le serveur ovh la source de libapache2-mod-php
http://nova.clouds.archive.ubuntu.com/ubuntu xenial/main php-defaults 35ubuntu6
de libapache2-mod-php7.0
http://nova.clouds.archive.ubuntu.com/ubuntu xenial-updates/main php7.0 7.0.22-0ubuntu0.16.04.1

**Questions :**
Sur quel hébergeur es-tu
Quel est la version exacte de Ubuntu
si tu tapes ` sudo aptitude search libapache2-mod-php`
qu'est ce qui s'affiche ?
et avec ` sudo aptitude show libapache2-mod-php` et ` sudo aptitude show libapache2-mod-php7.0`

**Comment by Patlol** [comment]
J'ai réinstallé depuis un serveur "frais" :) sur Ubuntu 16.04.2 LTS la totalité du serveur il n'y a pas eu d'erreur ou de plantage

**Comment by Salvitri** [comment]
C'est également une Ubuntu 16.04.2 LTS, mais sur un Kimsufi.
Les différentes commandes donnent :
`sudo aptitude search libapache2-mod-php`
```
i   libapache2-mod-php                                                                              - server-side, HTML-embedded scripting language (Apache 2 module) (default)
v   libapache2-mod-php:i386                                                                         -
i   libapache2-mod-php7.0                                                                           - server-side, HTML-embedded scripting language (Apache 2 module)
p   libapache2-mod-php7.0:i386                                                                      - server-side, HTML-embedded scripting language (Apache 2 module)

```
`sudo aptitude show libapache2-mod-php`
```
Package: libapache2-mod-php
State: installed
Automatically installed: no
Version: 1:7.0+35ubuntu6
Priority: optional
Section: php
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 15.4 k
Depends: libapache2-mod-php7.0
Provided by: libapache2-mod-php7.0 (7.0.22-0ubuntu0.16.04.1), libapache2-mod-php7.0 (7.0.4-7ubuntu2)
Description: server-side, HTML-embedded scripting language (Apache 2 module) (default)
 This package provides the PHP module for the Apache 2 webserver.

 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.

 This package is a dependency package, which depends on Debian's default PHP version (currently 7.0).
```
`sudo aptitude show libapache2-mod-php7.0`
```
Package: libapache2-mod-php7.0
State: installed
Automatically installed: no
Version: 7.0.22-0ubuntu0.16.04.1
Priority: optional
Section: httpd
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 4,328 k
Depends: libmagic1, mime-support, php7.0-cli, php7.0-common (= 7.0.22-0ubuntu0.16.04.1), php7.0-json, php7.0-opcache, tzdata, ucf, apache2-api-20120211, apache2-bin (>= 2.4.16), libc6 (>= 2.15), libpcre3,
         libssl1.0.0 (>= 1.0.2~beta3), libxml2 (>= 2.8.0), zlib1g (>= 1:1.1.4)
Recommends: apache2
Suggests: php-pear
Conflicts: libapache2-mod-php5 (< 5.6.16+dfsg-4~), libapache2-mod-php5:i386 (< 5.6.16+dfsg-4~), libapache2-mod-php5filter (< 5.6.16+dfsg-4~), libapache2-mod-php7.0:i386
Provides: libapache2-mod-php, phpapi-20151012
Description: server-side, HTML-embedded scripting language (Apache 2 module)
 This package provides the PHP module for the Apache 2 webserver (as found in the apache2-mpm-prefork package).  Please note that this package ONLY works with Apache's prefork MPM, as it is not compiled
 thread-safe.

 The following extensions are built in: Core date filter hash libxml openssl pcre Reflection session SPL standard zlib.

 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Homepage: http://www.php.net/
```
Ce qui paraît cohérent avec ce que tu dis.
Sauf que j'ai exécuté plusieurs fois le script et à chaque fois j'arrivais sur la même page que la personne qui a posté un autre billet :
![alt text](https://cloud.githubusercontent.com/assets/27552617/25063570/1054180e-21e8-11e7-9235-85d2d03d89b6.PNG)
Et le seul moyen de résoudre le problème ça a été de taper :
`sudo apt-get install libapache2-mod-php`
avant de lancer le script.

**Comment by Patlol** [comment]
ok je vois le problème, les dépôts ne doivent pas être les mêmes (merci ovh) 
donne moi tes dépôts : 
`sudo cat /etc/apt/sources.list`
les miens sont tous sous la forme 
`deb http://nova.clouds.archive.ubuntu.com/ubuntu/ xenial ...`
les dépôts officiels 
`deb http://fr.archive.ubuntu.com/ubuntu/ xenial  ...`

donc Monsieur nova.clouds aurait frappé ?
J'ai mis dans mes sources
`apt-get install libapache2-mod-php7.0 libapache2-mod-php ....`
en attendant de me pencher sur le sujet ...

**Comment by Salvitri** [comment]
Ah oui, en effet chez moi c'est :
`deb http://ubuntu.mirrors.ovh.net/ubuntu/ xenial ...`
Merci en tout cas !
